# Individual subscriber configuration:
#   name:           Source name
#   topic:          The topic that provides ackermann_cmd messages
#   timeout:        Time in seconds without incoming messages to consider this topic inactive
#   priority:       Priority: an UNIQUE unsigned integer from 0 (lowest) to MAX_INT 
#   short_desc:     Short description (optional)

subscribers:
  - name:        "Safety"
    topic:       "input/safety"
    timeout:     0.3
    priority:    15
    short_desc:  "Input for safety monitor, highest priority"
  - name:        "Teleoperation"
    topic:       "input/teleop"
    timeout:     0.3
    priority:    10
    short_desc:  "Input for human teleoperation (joystick)"
  - name:        "Navigation"
    topic:       "input/nav"
    timeout:     0.02
    priority:    3
    short_desc:  "Input for autonomous navigation"
  - name:        "Navigation2"
    topic:       "input/nav2"
    timeout:     0.02
    priority:    2
    short_desc:  "Input for autonomous navigation"
  - name:        "Navigation3"
    topic:       "input/nav3"
    timeout:     0.02
    priority:    1
    short_desc:  "Input for autonomous navigation"
  - name:        "Default"
    topic:       "input/default"
    timeout:     1.0
    priority:    0
    short_desc:  "Default input, lowest priority"
publisher:       "output"